### PR TITLE
Use site title for the home page

### PR DESCRIPTION
**Pull request by hawx**

### CODE REVIEW

**Comment by terrawheat** [comment]
I've not used Jekyll enough to know if this is practical but wouldn't it be nicer to do something like have a blank `page.title` and then use `{{ page.title or site.title }}` in the template?

That way any page could use the site title if it wants :)

**Comment by kevbite** [comment]
Looks fine just merge it in :-)

**Comment by hawx** [comment]
@terrawheat `page.title` is used for the header menu links, so a workaround would be needed to make that say "Home".

**Comment by terrawheat** [comment]
:+1: good enough for me :)

**Pull request merged**
